name: Compile latex slides
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used only to trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'rendu/presentation.tex'
     # - 'images/**'
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: rendu/presentation.tex
      - uses: actions/upload-artifact@v4
        with:
          name: presentation
          path: rendu/presentation.pdf
